### ISSUE TITLE
Invalid Markup

### ISSUE THREAD

**Issue by thevangelist** [visav/visav.github.io#1]
There are errors in markup. The [w3c validator](https://validator.w3.org/check?uri=http%3A%2F%2Fvisa.varjus.fi%2F&charset=%28detect+automatically%29&doctype=Inline&group=0) says there are `2 Errors`.

You can fix with them markup like this: [Example of HTML5 markup](http://www.sitepoint.com/a-minimal-html-document-html5-edition/), but exclude the script & css files.

**Comment by visav** [comment]
@thevangelist Thank you! :beer:

**Comment by thevangelist** [comment]
@visav no problem :shipit:
